# Site settings
name: Biao
email: ibiaowang@gmail.com
author: Biao Wang
url: http://www.hifreud.com
github: https://github.com/biaowang/
baseurl: ""
description: 音乐 诗词 代码 和舞蹈
meta_description: 个人博客;热爱生活
motto: Today is a gift.
banner: 博雅达观

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: biaowang

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9f

